version: "3"

services:
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    networks:
      - default
    image: wordpress
    container_name: "wordpress"
    environment:
      - WP_URL=https://${DOMAIN_NAME}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    networks:
      - default
    container_name: "mariadb"
    image: mariadb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped 

  nginx:
    build:
      context: ./requirements/nginx
    networks:
      - default
    container_name: "nginx"
    image: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTS_DIR=${CERTS_DIR}
      - TLS_VERSION=${TLS_VERSION}
      - PHP_FPM_HOST=${PHP_FPM_HOST}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped 

networks:
  default:
      name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${MYSQL_HOST_VOLUME_PATH}
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${WP_HOST_VOLUME_PATH}
      o: bind
