DELETE FROM	mysql.user WHERE User='';
DROP DATABASE test;
DELETE FROM mysql.db WHERE Db='test';
-- DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('mdesfont.42.fr', '127.0.0.1', '::1');
CREATE USER ${MYSQL_USER}@'%' IDENTIFIED by '${MYSQL_PASSWORD}';
CREATE DATABASE ${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON "${MYSQL_DATABASE}.*" TO "${MYSQL_USER}"@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';
