version: "3"

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/mdesfont/data/database
      type: volume
      o: bind
  wordpress:
    driver: local
    driver_opts:
      device: /home/mdesfont/data/wordpress
      type: volume
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/db/database/
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/
    restart: always
    networks:
      - default


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/
    restart: always
    networks:
      - default

networks:
  default:
