#docker-compose version, the 3 is the most use
version: '3'

services:

	mariadb:
		build:
			context: requirements/mariadb
		container_name: mariadb
		image: mariadb
		restart: always
		#copy db on the host disk, cause the db needs to be persistant
		volumes:
			- /data/mysql:/var/lib/mysql
		env_file:
			- ./.env

	wordpress:
		build:
			context: requirements/wordpress
		container_name: wordpress
		image: wordpress
		restart: always
		volumes:
			- /data/html:/var/www/html
		env_fils:
			./.env
		depends_on:
			- mariadb
		links:
			- mariadb