version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WEBROOT_PATH}/mariadb/:/var/db/mysql/
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - ${WEBROOT_PATH}/:/var/www/
    restart: always
    networks:
      - default


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ${WEBROOT_PATH}/:/var/www/
    restart: always
    networks:
      - default

networks:
  default:
